name: Automated Chaldal Scraper

on:
  schedule:
    # 02:00 UTC is 08:00 AM Bangladesh Time
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        # We tell GitHub to look inside the Chaldal folder for requirements.txt
        run: |
          pip install -r Chaldal/requirements.txt

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'
          install-chromedriver: true

      - name: Run Scraper
        # 'working-directory' moves the "active folder" into Chaldal
        working-directory: ./Chaldal
        run: |
          xvfb-run python Chaldal_scrape.py --input links.xlsx

      - name: Upload Data to GitHub Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Chaldal-Data-${{ github.run_id }}
          # We look for the CSV specifically inside the Chaldal folder
          path: Chaldal/chaldal_products_*.csv
